const RAW_BASE = 'https://raw.githubusercontent.com/andreschuindt/almacuidada-site/projetoinspira-production';
const RELEASE = '5.0';
const BUILD = '5.0.0';

const ROUTES = new Map([
  ['', 'index.html'],['index.html', 'index.html'],['livroterapia', 'livroterapia.html'],['livroterapia/', 'livroterapia.html'],['comunidade', 'comunidade.html'],['comunidade/', 'comunidade.html'],['empresas', 'empresas.html'],['empresas/', 'empresas.html'],['privacidade', 'privacidade.html'],['privacidade.html', 'privacidade.html'],['termos', 'termos.html'],['termos.html', 'termos.html']
]);
const TEXT_TYPES={html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'application/javascript; charset=utf-8',xml:'application/xml; charset=utf-8',txt:'text/plain; charset=utf-8',svg:'image/svg+xml; charset=utf-8',json:'application/json; charset=utf-8'};
const BINARY_TYPES={webp:'image/webp',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',ico:'image/x-icon',avif:'image/avif'};
const CSP=["default-src 'self'","base-uri 'self'","object-src 'none'","frame-ancestors 'none'","img-src 'self' data:","font-src 'self' data:","style-src 'self' 'unsafe-inline'","script-src 'self' 'unsafe-inline' https://va.vercel-scripts.com","connect-src 'self' https://vitals.vercel-insights.com https://va.vercel-scripts.com","form-action 'self' https://payfast.greenn.com.br","upgrade-insecure-requests"].join('; ');

function safePath(value){const clean=String(value||'').replace(/^\/+/, '').replace(/\/+/g,'/');if(!clean||ROUTES.has(clean))return ROUTES.get(clean)||'index.html';if(clean.includes('..')||clean.includes('\\')||clean.startsWith('api/'))return null;return clean;}
function contentType(path){const ext=path.split('.').pop().toLowerCase();return TEXT_TYPES[ext]||BINARY_TYPES[ext]||'application/octet-stream';}
function isHtml(path){return path.endsWith('.html');}
function setHeaders(res,path,status=200){res.statusCode=status;res.setHeader('Content-Type',contentType(path));res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=()');res.setHeader('Strict-Transport-Security','max-age=63072000; includeSubDomains; preload');res.setHeader('Content-Security-Policy',CSP);res.setHeader('X-Inspira-Release',RELEASE);res.setHeader('X-Inspira-Build',BUILD);if(isHtml(path))res.setHeader('Cache-Control','no-store, max-age=0');else if(/\.(css|js|webp|jpg|jpeg|png|svg|ico|avif)$/.test(path))res.setHeader('Cache-Control','public, max-age=31536000, immutable');else res.setHeader('Cache-Control','public, max-age=300, must-revalidate');}
async function fetchRaw(path){return fetch(`${RAW_BASE}/${path}`,{headers:{'User-Agent':'Projeto-INSPIRA/5.0'},redirect:'follow'});}
module.exports=async function handler(req,res){try{const url=new URL(req.url,'https://projetoinspira.vercel.app');const requested=url.searchParams.get('path')??url.pathname.replace(/^\/api\/proxy40\/?/,'');const path=safePath(requested);if(!path){setHeaders(res,'not-found.txt',404);return res.end('Not found');}const upstream=await fetchRaw(path);if(!upstream.ok){setHeaders(res,'not-found.html',upstream.status===404?404:502);return res.end(upstream.status===404?'<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Página não encontrada | INSPIRA</title><body><main><h1>Página não encontrada</h1><p><a href="/">Voltar ao Projeto INSPIRA</a></p></main></body></html>':'Falha temporária ao carregar o conteúdo.');}setHeaders(res,path,200);const type=contentType(path);if(type.startsWith('text/')||type.includes('javascript')||type.includes('xml')||type.includes('json')||type.includes('svg'))return res.end(await upstream.text());const bytes=Buffer.from(await upstream.arrayBuffer());res.setHeader('Content-Length',String(bytes.length));return res.end(bytes);}catch(error){console.error('INSPIRA 5.0 runtime error',error);setHeaders(res,'error.txt',500);return res.end('Erro temporário. Tente novamente em instantes.');}};