questions.push(...[
  {id:"q11",domain:"conectar",difficulty:4,stimulus:"Texto A: 'A leitura em tela facilita o acesso rápido a muitos conteúdos.'\n\nTexto B: 'Quando notificações interrompem a leitura, manter a atenção por longos períodos pode se tornar mais difícil.'",prompt:"Qual conclusão integra adequadamente os dois textos?",options:["Ler em tela é sempre pior","O ambiente digital amplia o acesso, mas pode trazer desafios de atenção","Notificações melhoram a concentração","Somente livros impressos permitem aprender"],correct:1,rationale:"A resposta preserva as duas ideias sem transformar nenhuma delas em afirmação absoluta."},
  {id:"q12",domain:"conectar",difficulty:4,stimulus:"Texto: 'Durante três meses, o projeto abriu a biblioteca até as 21h. Nesse período, aumentou a presença de trabalhadores que não conseguiam frequentá-la no horário comercial.'",prompt:"Qual conclusão conecta corretamente o horário ampliado ao aumento de presença?",options:["Todos os trabalhadores passaram a frequentar a biblioteca","O horário ampliado removeu uma barreira para parte do público","A biblioteca ficou vazia durante o dia","O projeto eliminou todas as dificuldades de acesso à leitura"],correct:1,rationale:"O aumento de presença após a ampliação de horário sustenta a conclusão de redução de uma barreira específica."},
  {id:"q13",domain:"avaliar",difficulty:4,stimulus:"Anúncio: '9 em cada 10 pessoas preferem nosso produto!'\nEm letras pequenas: 'Pesquisa online com 20 participantes selecionados entre clientes da própria marca.'",prompt:"Qual é a principal razão para interpretar a afirmação do anúncio com cautela?",options:["O anúncio contém números","A amostra é pequena e formada apenas por clientes da marca","A pesquisa foi feita online","O produto tem uma marca"],correct:1,rationale:"A forma de seleção e o tamanho da amostra limitam a força da generalização."},
  {id:"q14",domain:"avaliar",difficulty:4,stimulus:"Postagem: 'Meu vizinho tomou um chá e melhorou da gripe em dois dias. Portanto, esse chá cura gripe.'",prompt:"Qual problema existe no raciocínio da postagem?",options:["Ela apresenta um exemplo individual como prova suficiente de uma conclusão geral","Ela usa uma frase curta","Ela menciona um vizinho","Ela fala sobre uma bebida quente"],correct:0,rationale:"Um caso isolado não estabelece, por si só, uma relação causal geral."},
  {id:"q15",domain:"avaliar",difficulty:5,stimulus:"Texto 1: 'A prefeitura afirma que a nova ciclovia reduziu acidentes na avenida.'\nTexto 2: 'O relatório apresentado pela prefeitura compara apenas dois meses antes e dois meses depois da obra, sem ajustar diferenças no volume de tráfego.'",prompt:"Qual avaliação é mais adequada?",options:["A ciclovia certamente não funciona","A afirmação da prefeitura é necessariamente falsa","Os dados podem sugerir melhora, mas o método descrito limita conclusões firmes","Qualquer comparação antes/depois é inválida"],correct:2,rationale:"A resposta reconhece a evidência disponível e, ao mesmo tempo, a limitação metodológica."},
  {id:"q16",domain:"avaliar",difficulty:5,stimulus:"Título: 'Estudo prova que trabalhar em casa aumenta a produtividade.'\nResumo: 'A pesquisa acompanhou 42 profissionais voluntários de uma única empresa de tecnologia durante três semanas.'",prompt:"Qual reescrita seria mais responsável?",options:["Trabalho remoto sempre aumenta a produtividade","Estudo com 42 voluntários de uma empresa encontrou aumento de produtividade no período observado","Tecnologia prova que escritórios não funcionam","Todos os trabalhadores devem trabalhar em casa"],correct:1,rationale:"A reescrita mantém o achado e explicita limites de amostra e contexto."},
  {id:"q17",domain:"aplicar",difficulty:2,stimulus:"PROMOÇÃO\nCaderno: R$ 30\nDesconto de 20% somente para compras feitas pelo aplicativo.",prompt:"Uma pessoa compra o caderno pelo aplicativo. Quanto paga?",options:["R$ 6","R$ 20","R$ 24","R$ 28"],correct:2,rationale:"20% de R$30 são R$6; portanto, o preço final é R$24."},
  {id:"q18",domain:"aplicar",difficulty:3,stimulus:"AGENDA\n09:00 — reunião de equipe (45 min)\n10:00 — atendimento ao cliente (30 min)\n11:00 — treinamento (1h30)",prompt:"Qual compromisso termina mais tarde?",options:["Reunião de equipe","Atendimento ao cliente","Treinamento","Todos terminam no mesmo horário"],correct:2,rationale:"O treinamento começa às 11h e dura 1h30, terminando às 12h30."},
  {id:"q19",domain:"aplicar",difficulty:4,stimulus:"Site de inscrição:\n1. Preencha seus dados.\n2. Confirme o e-mail pelo link recebido.\n3. Escolha uma turma.\n4. Finalize a inscrição.\n\nMensagem na tela: 'E-mail ainda não confirmado.'",prompt:"Qual é a próxima ação necessária para continuar o processo?",options:["Escolher uma turma","Preencher os dados novamente","Abrir o e-mail e usar o link de confirmação","Finalizar a inscrição"],correct:2,rationale:"A sequência depende da confirmação do e-mail antes da escolha de turma."},
  {id:"q20",domain:"aplicar",difficulty:5,stimulus:"PLANO A: R$ 49/mês, cancelamento a qualquer momento.\nPLANO B: R$ 39/mês, contratação mínima de 12 meses e multa de 30% sobre as mensalidades restantes em caso de cancelamento antecipado.",prompt:"Uma pessoa valoriza principalmente liberdade para cancelar sem custo. Qual plano atende melhor a esse critério?",options:["Plano A","Plano B","Os dois são equivalentes nesse critério","Não é possível comparar"],correct:0,rationale:"O Plano A permite cancelamento a qualquer momento; o Plano B prevê compromisso e multa."}
]);